### ISSUE TITLE
Enable branch protection on master

### ISSUE THREAD

**Issue by tkelman** [bramtayl/ChainMap.jl#1]
It looks like you may have done a force push which undid about 10 commits from Oct 31st and Nov 1st. It's usually recommended not to force push to master as it can cause the local repos of anyone who has checked out master locally and does a pull to get out of sync.

**Comment by bramtayl** [comment]
Ok, just enabled it. I had made a whole bunch of deletions trying to make the package simpler but eventually decided to keep it as is. I tried to git reset without --hard but then there was a whole bunch of conflicts to fix and I got confused. I hope I didn't cause any problems for anyone? PS I tried to tag and publish but I ran into #18113.

**Comment by tkelman** [comment]
As long as you didn't remove any of the tagged commits you should be fine. It's only a problem if anyone had the package locally checked out to master. I think there's a chart under graphs you can view that tells you how many clones (and how many uniques) the package gets.

as far as 18113 goes, see https://github.com/JuliaLang/julia/issues/18113#issuecomment-254263390
